### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by c42f** [JuliaArrays/StaticArrays.jl#532]
As discussed over at #522, it's almost time for a 1.0.0 release. Personally I think there should be no great breaking changes here and we should try to make it compatible with the status quo of the last year or so. However, we can take the opportunity to make it as consistent with the final state of julia-1.0 Base as possible via a few targeted deprecations (with proper depwarns).

Here's a TODO list (moved from prior discussion at #522).  Feel free to add or suggest items.

* [x] Triage past issues & add any v1.0 milestones
* [x] Triage current PRs & add any v1.0 milestones
* [x] Deprecations
  * [x] Remove v0.9 deprecations (#525)
  * [x] Deprecate `SDiagonal` in favor of `Base.Diagonal` #531
  * [x] Remove deprecated FixedSizeArrays module
* [x] A way forward for constructors
  * [x] Make sure we have a strategy for #518 (probably #633 or #636)
  * [x] ~~Deprecate (most of?) the zoo of constructor macros (replace with #633 ?) but keep them around in the 1.0 release cycle.~~ Can be soft-deprecated later
  * [x] ~~Constructors with generators or ntuple like syntax #97~~ Can be done later
  * [x] Fix #520
  * [x] Fix #557
* [ ] ~~Revisit `axes`; `SUnitRange` etc to consider whether these design changes should go into 1.0~~ Too big for 1.0
  * [ ] ~~Tidy up usage of `SOneTo` (follow up of #534; see also #620)~~
  * [ ] ~~Export of `SUnitRange` #474~~
  * [ ] ~~Consider modernizing & merging #150~~
* [x] Resolve fallout from #503 where possible (eltype becoming `Union{}`) cf. #528
* [x] Consider whether we can avoid promoting MArray to SArray quite so often #327

**Comment by musm** [comment]
Presumably the FixedSizedArrays compatibility layer can also be removed?

**Comment by mschauer** [comment]
Yes, it is deprecated and was vendorised in the only dependence: https://github.com/JuliaGeometry/GeometryTypes.jl/pull/153

**Comment by c42f** [comment]
Good idea, see #600.

**Comment by chakravala** [comment]
Will release v1.0.0 have any breaking changes?

**Comment by c42f** [comment]
Probably a few more deprecations to come during cleanup but nothing specifically on my mind. Currently it seems that bumping major versions of widely used packages is a bit more disruptive than would be ideal, so it would seem best to wait until we have a batch of breaking changes.

There's no plan for a major rewrite or large change in the APIs though; it's mostly incremental maintenance at this stage.

**Comment by tkoolen** [comment]
Just wanted to say thanks for all the effort you've put into the package lately, @c42f!

**Comment by c42f** [comment]
Thanks Twan, I'm slowly chipping away at cleaning a few dark corners of the implementation :-)

**Comment by mateuszbaran** [comment]
Could we have https://github.com/JuliaArrays/StaticArrays.jl/pull/783 in 1.0?

**Comment by c42f** [comment]
Yes indeed :+1:

**Comment by chakravala** [comment]
What's the 1.0 timeline?

**Comment by c42f** [comment]
No specific timeline. Releasing major versions is kinda disruptive so I wanted to make the 0.12 -> 1.0 transition "worthwhile" in that it cleaned up a few things at once.

But resolving all of the big list of "desirable issues" above is more than I can bite off at the moment, so at this point I think it might be best just to make 1.0 the next major release (in the near future) and deal with the thorny problem of `axes` and `SUnitRange` later on.

Looking back at the list of issues at the top of this thread, most of them are more desirable than necessary for 1.0 anyway, as many are bug fixes and other things which aren't breaking.

What do you think @andyferris?

**Comment by andyferris** [comment]
We should clean up the macros a bit, probably. I see what you mean by a lot being desirables. Honestly - a fundamental change like a really good treatment of axes/keys might warrant a future 2.0 release if it turns out to break dependent packages. Basically I’m in on your plan, @c42f.

**Comment by c42f** [comment]
Agreed it would be nice to clean up the macros somewhat, maybe deprecating a little questionable functionality if there's any left.

My general thoughts about the macros are that we're still not in a position to deprecate them soon because we haven't landed on a satisfying solution for things like `@SVector rand(4)`. This syntax is just *so darn attractive* because it exactly mirrors the Base syntax which makes it really easy to remember, and I see people using it constantly. Of course it's pretty dissatisfying in other ways, but until a better alternative appears...

**Comment by c42f** [comment]
> Of course it's pretty dissatisfying in other ways, but until a better alternative appears

Well, @tkf just reminded me about StaticNumbers.jl; I suppose the "correct" solution in some sense would be `rand(static(4))`. Still not ideal for syntax but at least it has semantics which exactly mirror `Random.rand`.

**Comment by tkf** [comment]
I was jus writing "Why not `rand(static(4))`" :smile: 

Alternatively, maybe we can use `rand(SVector{4})` if Random.jl starts allowing `rand(NTuple{5,Int})` https://github.com/JuliaLang/julia/pull/35856?

**Comment by c42f** [comment]
> Alternatively, maybe we can use `rand(SVector{4})

Actually this already works. But I've never felt really happy that it's semantically compatible with Base so I don't think it's a replacement.

**Comment by tkf** [comment]
Oops, I should've checked if it works before posting it.  But why it's not a replacement?  I think it'd be nice if you can get a random data structure with a generic API like `rand(data_structure_with_holes)` where a type is one way to specify a `data_structure_with_holes`.

**Comment by c42f** [comment]
Sure, it's fine in that sense, and it's quite compatible in meaning with things like `rand(UInt32)` so I shouldn't be too dissatisfied :-)  Perhaps it's more just a user interface thing - it's nice to have an analogy to Base which is as exact as possible in terms of the syntax for generating random `Array`s. As far as I've noticed people do prefer writing `@SVector rand(4)` over `rand(SVector{4})`.

**Comment by tkf** [comment]
I don't think shooting for `Array`-compatible API like `rand(4)` scales well.  There are too many places `Array`s are special-cased (perhaps rightly so).  I think it's better to have a predictable API that composes well.

Having said that, it _may_ be reasonable for `SArray` to be special-cased since it is probably the most frequently used non-wrapper array type.

**Comment by mateuszbaran** [comment]
Are there any changes needed for 1.0? Or could we have it released?

**Comment by c42f** [comment]
I think if you need it, it's probably best to release it.

Obviously I'd like to have time to fix more things and carefully assess the state of it ;-) But I don't have it, and I can't see anything really blocking holding us up.

**Comment by mateuszbaran** [comment]
I don't strictly need it, I'd just like to make some cleanup in HybridArrays.jl and Manifolds.jl that depends on `SizedArray` changes and structured matrix multiplication. For example I am seriously thinking about copying `SizedArray` to HybridArrays.jl to fix this issue: https://github.com/mateuszbaran/HybridArrays.jl/pull/23 . So for example I'd like to know if it's worth waiting for the next version of StaticArrays or should I just copy that code?

**Comment by c42f** [comment]
Sounds like you need it to me! Let's release.

**Comment by c42f** [comment]
https://github.com/JuliaRegistries/General/pull/25375

**Comment by andyferris** [comment]
Yay!

So, our work here is done, right? :)

**Comment by mateuszbaran** [comment]
Thanks! I hope there won't be too many problems across the ecosystem :slightly_smiling_face: .
